# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paul Anderson, Web Developer
email: paul@andersonpaul.com
description: > # this means to ignore newlines until "baseurl:"
  The personal site and portfolio of B. Paul Anderson, a front-end web developer
  focusing on modern JavaScript, abstraction, and simplicity
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bpaulanderson
github_username:  b-paul

# Build settings
markdown: kramdown
